name: Build MonQuest ROM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install GBDK-2020
        run: |
          wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.2.0/gbdk-linux64.tar.gz
          tar -xzf gbdk-linux64.tar.gz
          echo "$(pwd)/gbdk/bin" >> $GITHUB_PATH

      - name: Build ROM
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MonQuest
          path: monquest.gb
